package com.mycompany.vehicula;

import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author at11DAM2
 */
public class Vehiculo extends javax.swing.JFrame {

    /**
     * Creates new form Vehiculo
     */
    public Vehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpV = new javax.swing.ButtonGroup();
        btngrp2 = new javax.swing.ButtonGroup();
        btngrpCombusible = new javax.swing.ButtonGroup();
        txtmarca = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        chkCoche = new javax.swing.JCheckBox();
        chkMoto = new javax.swing.JCheckBox();
        chkCamion = new javax.swing.JCheckBox();
        chlCapota = new javax.swing.JCheckBox();
        chkRemolque = new javax.swing.JCheckBox();
        chkSidecar = new javax.swing.JCheckBox();
        btnMostrar = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        RbtDiesel = new javax.swing.JRadioButton();
        RbtGasolina = new javax.swing.JRadioButton();
        RbtEléctrico = new javax.swing.JRadioButton();
        CboxColor = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCoches = new javax.swing.JTable();
        btnAñadir = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMarca.setText("Marca");

        lblModelo.setText("Modelo");

        btngrpV.add(chkCoche);
        chkCoche.setText("Coche");
        chkCoche.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkCocheItemStateChanged(evt);
            }
        });
        chkCoche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkCocheMouseClicked(evt);
            }
        });
        chkCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCocheActionPerformed(evt);
            }
        });

        btngrpV.add(chkMoto);
        chkMoto.setText("Moto");
        chkMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMotoActionPerformed(evt);
            }
        });

        btngrpV.add(chkCamion);
        chkCamion.setText("Camión");
        chkCamion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkCamionMouseClicked(evt);
            }
        });

        btngrp2.add(chlCapota);
        chlCapota.setText("Capota");
        chlCapota.setEnabled(false);
        chlCapota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chlCapotaActionPerformed(evt);
            }
        });

        btngrp2.add(chkRemolque);
        chkRemolque.setText("Remolque");
        chkRemolque.setEnabled(false);

        btngrp2.add(chkSidecar);
        chkSidecar.setText("Sidecar");
        chkSidecar.setEnabled(false);

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btngrpCombusible.add(RbtDiesel);
        RbtDiesel.setText("Diesel");

        btngrpCombusible.add(RbtGasolina);
        RbtGasolina.setText("Gasolina");

        btngrpCombusible.add(RbtEléctrico);
        RbtEléctrico.setText("Eléctrico");

        CboxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amarillo", "Rojo", "Verde", "Azul" }));

        tblCoches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Vehículo", "Accesorio", "Combustible", "Color"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCoches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCochesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCoches);

        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar Fila");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCoche)
                            .addComponent(chkMoto)
                            .addComponent(chkCamion))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkSidecar)
                            .addComponent(chkRemolque)
                            .addComponent(chlCapota))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RbtGasolina)
                            .addComponent(RbtEléctrico)
                            .addComponent(RbtDiesel)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblMarca)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtmarca))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblModelo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CboxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnMostrar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnClear)))
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBorrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAñadir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(chkCoche)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chkMoto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chkCamion))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(chlCapota)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chkRemolque)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chkSidecar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RbtDiesel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RbtGasolina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RbtEléctrico)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CboxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnMostrar)
                                    .addComponent(btnClear)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAñadir)
                            .addComponent(btnBorrar))
                        .addGap(287, 287, 287))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCocheActionPerformed

    private void chlCapotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chlCapotaActionPerformed
             // TODO add your handling code h
    }//GEN-LAST:event_chlCapotaActionPerformed

    private void chkCocheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkCocheMouseClicked
    chlCapota.setEnabled(true);
    chkRemolque.setEnabled(false);
    chkSidecar.setEnabled(false);
    btngrp2.clearSelection();
    }//GEN-LAST:event_chkCocheMouseClicked

    private void chkMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMotoActionPerformed
    chlCapota.setEnabled(false);
    chkRemolque.setEnabled(false);
    chkSidecar.setEnabled(true);
    
    btngrp2.clearSelection();
    
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMotoActionPerformed

    private void chkCamionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkCamionMouseClicked
    chlCapota.setEnabled(false);
    
    chkRemolque.setEnabled(true);
    chkSidecar.setEnabled(false);  
    
    btngrp2.clearSelection();// TODO add your handling code here:
    }//GEN-LAST:event_chkCamionMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtModelo.setText("");
        txtmarca.setText("");
        
        btngrpV.clearSelection();
        btngrp2.clearSelection();
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        System.out.println("Marca: "+txtmarca.getText()+" Modelo: "+txtModelo.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void chkCocheItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkCocheItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCocheItemStateChanged

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        String vehiculo;
        String accesorio;
        String combustible;
        
        if (chkCamion.isSelected())
            vehiculo = chkCamion.getText();
        else if (chkCoche.isSelected())
            vehiculo = chkCoche.getText();
        else if (chkMoto.isSelected())
            vehiculo = chkMoto.getText();
        else
            vehiculo ="";
        
        if (chlCapota.isSelected())
            accesorio = chlCapota.getText();
        else if (chkRemolque.isSelected())
            accesorio = chkRemolque.getText();
        else if (chkSidecar.isSelected())
            accesorio = chkSidecar.getText();
        else 
            accesorio ="sin accesorio";
        
        if (RbtDiesel.isSelected())
            combustible = RbtDiesel.getText();
        else if (RbtEléctrico.isSelected())
            combustible = RbtEléctrico.getText();
        else if (RbtGasolina.isSelected())
            combustible = RbtGasolina.getText();
        else combustible="Sin especificar";
        
      DefaultTableModel modeloDatos = (DefaultTableModel)tblCoches.getModel();      
      modeloDatos.addRow(new Object[]{txtmarca.getText(),txtModelo.getText(),vehiculo,accesorio,combustible,CboxColor.getSelectedItem()});
        btngrpV.clearSelection();
        btngrp2.clearSelection();
        txtModelo.setText("");
        txtmarca.setText("");
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
       try{
      
           
       DefaultTableModel modeloDatos = (DefaultTableModel)tblCoches.getModel();
       int filaSeleccionada = tblCoches.getSelectedRow();
       modeloDatos.removeRow(filaSeleccionada);
       JOptionPane.showMessageDialog(this, "Elemento borrado con éxito");
       
       }catch (ArrayIndexOutOfBoundsException e){
            if(tblCoches.getRowCount()<1)
           JOptionPane.showMessageDialog(this, "La tabla está vacia");
           else
           JOptionPane.showMessageDialog(this, "No se ha seleccionado ninguna fila");
       }
       
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void tblCochesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCochesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCochesMouseClicked

    /**
     * @param args the command line arguments 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboxColor;
    private javax.swing.JRadioButton RbtDiesel;
    private javax.swing.JRadioButton RbtEléctrico;
    private javax.swing.JRadioButton RbtGasolina;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnMostrar;
    private javax.swing.ButtonGroup btngrp2;
    private javax.swing.ButtonGroup btngrpCombusible;
    private javax.swing.ButtonGroup btngrpV;
    private javax.swing.JCheckBox chkCamion;
    private javax.swing.JCheckBox chkCoche;
    private javax.swing.JCheckBox chkMoto;
    private javax.swing.JCheckBox chkRemolque;
    private javax.swing.JCheckBox chkSidecar;
    private javax.swing.JCheckBox chlCapota;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JTable tblCoches;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtmarca;
    // End of variables declaration//GEN-END:variables
}
